name: Trigger auto deployment for vciso-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature/vciso-engine ]
    paths:
    - '**'
    - '.github/workflows/vciso-app-AutoDeployTrigger-144cdf71-861b-44fa-92d8-37238a68377c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VCISOAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VCISOAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VCISOAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrvcisoaudit.azurecr.io
          registryUsername: ${{ secrets.VCISOAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VCISOAPP_REGISTRY_PASSWORD }}
          containerAppName: vciso-app
          resourceGroup: Bradley
          imageToBuild: acrvcisoaudit.azurecr.io/vciso-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


